image: python:latest

test:
  stage: test
  only:
    - master
  script:
    - pip install mkdocs-material
    - pip install mkdocs-bibtex
    - mkdocs build --strict --verbose --site-dir mkdocs_test
  artifacts:
    paths:
    - test

pages:
  stage: deploy
  only:
    - master 
  script:
    - pip install mkdocs-material
    - pip install mkdocs-bibtex
    - mkdocs build --verbose --site-dir public
  artifacts:
    paths:
      - public
      