# run: conda env create --file environment.yml
name: deepcv
channels:
- conda-forge
- defaults
dependencies:
- python=3.10.6
- tensorflow-gpu=2.10.0
- numpy=1.23.1
- scipy=1.9.1
- scikit-learn=1.1.2
- sympy=1.11.1
- matplotlib=3.6.1
- bayesian-optimization=1.2.0
- imageio=2.22.0
- natsort=8.2.0
- tabulate=0.9.0
- tqdm=4.64.1
- pydot=1.4.2
- pip
- pip:
  - tensorflow-addons==0.18.0
  - ase==3.22.1
