# create env: conda env create --file environment.yml
# update env: conda env update --file environment --prune
name: deepcv
channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pip
- tensorflow
- numpy
- scipy
- scikit-learn
- matplotlib
- ase
- imageio
- natsort
- tabulate
- tqdm
- pydot
- graphviz
