site_name: DeepCV
site_description: DeepCV - Deep Learning Framework for Discovering Collective Variables
site_url: https://lubergroup.pages.uzh.ch/deepcv
site_dir: public
site_author: Luber Group, UZH

repo_url: https://gitlab.uzh.ch/lubergroup/deepcv
repo_name: GitLab

theme:
  name: material
  features:
    - navigation.sections

nav:
  - Introduction: 
    - DeepCV: index.md
    - DAENN: introduction/daenn.md
    - Descriptors: introduction/descriptors.md
  - Installation:
    - Overview: installation/overview.md
    - Environment setup: installation/env-setup.md
    - Install: installation/install.md
    - Compile: installation/compile.md
  - Usage:
    - 1. Overview: 
      - Understand DeepCV: usage/overview.md
      - DeepCV modules: usage/modules.md
    - 2. Prepare dataset: usage/prepare-dataset.md
    - 3. Prepare DeepCV input file: usage/input-file.md
    - 4. Train DAENN model with DeepCV: usage/training-model.md
    - 5. Enhanced sampling:
      - Metadynamics using PLUMED: usage/metad-sim.md
      - CP2K with PLUMED: usage/cp2k-with-plumed.md
      - Run CP2K on SLURM cluster: usage/slurm-cp2k.md
    - 6. Post-analysis:
      - Free energy surface: usage/fes-analysis.md
      - Metastable states: usage/states-analysis.md
  - Cite DeepCV: citing.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/ref.bib"
      # cite_style: "pandoc"

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.extra
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
